### ISSUE TITLE
Crash on using ANY portal, ANY dimension

### ISSUE THREAD

**Issue by ProfessionaFiddler** [Pannoniae/sodium-forge#14]
Just did a standalone Sodium test:

Forge 35.1.5 / Minecraft 1.16.4
Classic world generation, crash upon entering selfbuilt nether portal.
Crash Log:
[crash-2021-01-16_11.15.30-server.txt](https://github.com/Pannoniae/sodium-forge/files/5824179/crash-2021-01-16_11.15.30-server.txt)

**Comment by ProfessionaFiddler** [comment]
I will give more detaiös in due time

**Comment by ProfessionaFiddler** [comment]
Just did a standalone Sodium test:

Forge 35.1.5 / Minecraft 1.16.4
Classic world generation, crash upon entering selfbuilt nether portal.
Crash Log:
[crash-2021-01-16_11.15.30-server.txt](https://github.com/Pannoniae/sodium-forge/files/5824176/crash-2021-01-16_11.15.30-server.txt)

**Comment by ProfessionaFiddler** [comment]
Is Lithium trying to generate villages in the Nether?

**Comment by ProfessionaFiddler** [comment]
hello..?

**Comment by yatsukiko** [comment]
Can you try this? [sodium-forge-1.1.jar](https://yatsukiko.me/u/sodium-forge-1.1.jar) crash is related to "point of interest" which at the time of making this fork was kind of broken already

**Comment by ProfessionaFiddler** [comment]
on it

**Comment by ProfessionaFiddler** [comment]
Yes, that version works (even in 1.16.5), many thanks

**Comment by ProfessionaFiddler** [comment]
Um, but now the water textures are gone. (EDIT: only if options are set to Fabilous, false alarm)

**Comment by yatsukiko** [comment]
Yeah in fabulous any texture that's 50% transparent is invisible
