### ISSUE TITLE
Curse Release

### ISSUE THREAD

**Issue by KubiRemPL** [Pannoniae/sodium-forge#16]
**Is your feature request related to a problem? Please describe.**

I would like to include yours mod in my modpack (not released) without any issues 

**Describe the solution you'd like**

Put mod on curse

**Describe alternatives you've considered**

Nothing that I can think of on 1.16, but on 1.12.2 there was a mod that could download anything from github or other sites into mods folder after modpack was installed.

**Additional context**

Nothing

**Comment by yatsukiko** [comment]
Not planned as of now.
