### ISSUE TITLE
Partial incompatibility with Create

### ISSUE THREAD

**Issue by nooneisback** [Pannoniae/sodium-forge#18]
Many tile entities do not render.

### Screenshots with and without this mod
![2021-02-04_12 34 29](https://user-images.githubusercontent.com/54672477/106888366-c0e9ef80-66e6-11eb-8f58-13ace9924aef.png)
![2021-02-04_12 36 03](https://user-images.githubusercontent.com/54672477/106888371-c2b3b300-66e6-11eb-86e6-5721619153b3.png)

### System Information

- Java Version: 1.8.0_271-b09
- CPU: i7 7700HQ
- GPU: GTX 1070

**Comment by samdev-7** [comment]
Same issue

**Comment by TheSunCat** [comment]
Can reproduce (same artifacts). It improves my performance near Create structures from ~20fps to 200fps but with the tradeoff of not rendering many of the blocks.

Java Version: OpenJDK 15.0.2
CPU: i7 7700
GPU: RTX 3060Ti

**Comment by yatsukiko** [comment]
It's linked with not being able to render multiparts, please check new version should be fixed

**Comment by samdev-7** [comment]
Yep fixed.
