### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Sharkie124** [Pannoniae/sodium-forge#19]
I'm not saying you have to add this since it isn't with Sodium (KEEP READING) but I have an idea. What if you made an exclusive version with some OptiFine settings like the transparent leaves, zoom feature and dynamic lights. It would be really nice to make an exclusive version with some extra features that Sodium doesn't yet have.

**Comment by yatsukiko** [comment]
OptiFine is closed source, manually writing features like these is effort and this forge fork isn't about adding new features, you may have more luck at HalogenMods/Chlorine instead, nothing guaranteed tho.
