### ISSUE TITLE
Some animated models not rendering correctly

### ISSUE THREAD

**Issue by samdev-7** [Pannoniae/sodium-forge#22]
### Expected Behavior
The models are animated without a overlapping static one. 
Example with the [Create Mod](https://www.curseforge.com/minecraft/mc-mods/create):
![Expected Behavior](https://user-images.githubusercontent.com/66446458/107889832-3a51c100-6ee3-11eb-848d-38d6ec810eb2.gif)

### Actual Behavior
Although the models are succefully turning, there seems to be a static model.
Example with the [Create Mod](https://www.curseforge.com/minecraft/mc-mods/create): 
![Actual Behavior](https://user-images.githubusercontent.com/66446458/107890070-f2cc3480-6ee4-11eb-9a79-97a2f210bd13.gif)

### Reproduction Steps
(Using the [Create Mod](https://www.curseforge.com/minecraft/mc-mods/create))

1. Place a shaft or cog in any direction
2. Power the Shaft/Cog
3. Issue occurs 

### Information
Mods: [Create Mod V0.3e (1.16.4)](https://www.curseforge.com/minecraft/mc-mods/create/files/3167531), [Sodium Forge 2.0](https://github.com/Pannoniae/sodium-forge/releases/tag/0.2)
Minecraft Version: 1.16.4 Singleplayer
System: MacOS (Version: 10.15.7 (19H2))
Java Version: 1.8.0_74 64bit
CPU: 1.4 GHz Quad-Core Intel Core i5
GPU: Intel Iris Plus Graphics 645 1536 MB

**Comment by yatsukiko** [comment]
can you try this? https://yatsukiko.me/u/sodium-forge-2.1.jar

**Comment by samdev-7** [comment]
Seems to be fixed with that new jar!
