### ISSUE TITLE
Crash when loading game

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Pannoniae/sodium-forge#23]
### Reproduction Steps
Crash happens before reaching the main menu.

### Crash Report File
https://gist.githubusercontent.com/SirOMGitsYOU/dcc0aa5c4defd0257b32996818018c9d/raw/c64bc3dd1c93fede0c4a56511f626d1b401332e5/gistfile1.txt

### Additional Information
Can provide modlist if needed but can be found in the crash report at the bottom.

**Comment by yatsukiko** [comment]
one of your mods overwrites a method to be public while sodium try to access that when its private, can you try this build? https://yatsukiko.me/u/sodium-forge-2.0.jar

**Comment by SirOMGitsYOU** [comment]
> one of your mods overwrites a method to be public while sodium try to access that when its private, can you try this build? https://yatsukiko.me/u/sodium-forge-2.0.jar

https://i.imgur.com/3MNq6iY.png

**Comment by yatsukiko** [comment]
sodium is a 1.16.5 mod? not 1.12.2

**Comment by SirOMGitsYOU** [comment]
> sodium is a 1.16.5 mod? not 1.12.2

My bad I had loaded it up with the wrong instance. That version you sent me works fine thank you :)

**Comment by SirOMGitsYOU** [comment]
> > sodium is a 1.16.5 mod? not 1.12.2
> 
> My bad I had loaded it up with the wrong instance. That version you sent me works fine thank you :)

Scratch that it just crashed when trying to generate a world. 
[crash-2021-02-19_13.28.34-client.txt](https://github.com/Pannoniae/sodium-forge/files/6010284/crash-2021-02-19_13.28.34-client.txt)
