### ISSUE TITLE
Ticking entity issue with guard villagers

### ISSUE THREAD

**Issue by rakostep** [Pannoniae/sodium-forge#30]
### Reproduction Steps
1. Have Sodium Forge 2.1(nether fix build) installed on a server with guard villager mod
2. Load world
3. Go to a village
4. Server will crash

### Crash Report File
N/A (can't provide since it was not me that triggered it, but I have encountered this issue before and reported it here on the earlier versions.)

**Comment by yatsukiko** [comment]
can you try this? https://yatsukiko.me/u/sodium-forge-2.1.jar

**Comment by rakostep** [comment]
> can you try this? https://yatsukiko.me/u/sodium-forge-2.1.jar

Hi again, yes this works on our server now, thank you very much for your hard work!
