### ISSUE TITLE
Fabric port

### ISSUE THREAD

**Issue by Genau6502** [Pannoniae/sodium-forge#4]
I really want this ported to the modern and great mod loader that is fabric, would be really cool to see

If you could make a fabric mod jar for this it would be epic

Optifabric is bad, but this is really promising, just doesn't support fabric
**Additional context**

**Comment by ghost** [comment]
This mod is already made for fabric and this is a forge port of it (You can see it is forked from  jellysquid3/sodium-fabric) https://github.com/jellysquid3/sodium-fabric (sorry for bad english).
