### ISSUE TITLE
World never loads

### ISSUE THREAD

**Issue by Unusual-Danger** [Pannoniae/sodium-forge#42]
### Expected Behavior
Replace this text with what you expected to happen.
I should be able to join a world and play.

### Actual Behavior
Replace this text with what actually happened.
I'm never able to join the world
### Reproduction Steps
Provide information on how to reproduce this game crash. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear! If applicable, please provide a world file as a compressed ZIP which contains a minimally reproducible example of the issue. 

1. Install the mod and put it in the mods folder
2. Join a single player world 
3. World never loads

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: Java 8 Update 291
- CPU: Intel i5-8250U 1.6Ghz
- GPU: Intel UHD 620

**Comment by Unusual-Danger** [comment]
Made the mod work however another sever issue occurred

**Comment by bucktt** [comment]
My guy can you elaborate on how you made it work? I really want this bundled pile of goodness to be used in my world

**Comment by Unusual-Danger** [comment]
I believe I changed the GL engine to 1 lower and it seemed to fix it. Can’t really remember

**Comment by bucktt** [comment]
Well that didn't work for me. What DID work however, was turning everything except for the 2nd to the last option off, then enabling it all in-game. So whoever is having this issue of their world not loading, hopefully that works
