### ISSUE TITLE
1.8.9 forge?

### ISSUE THREAD

**Issue by SkylineHack** [Pannoniae/sodium-forge#49]
Does this support 1.8.9 forge?

**Comment by embeddedt** [comment]
This is for 1.16. As far as I know, the renderer implementation is significantly different in 1.8, so backporting would likely be a monumental task.

Personally, I find OptiFine to give similar performance on 1.8 to what Sodium gives on 1.16.

**Comment by yatsukiko** [comment]
you are asking to backport a mod to a mc version from 6 years ago?
