### ISSUE TITLE
[CRASH REPORT] Random client crash.

### ISSUE THREAD

**Issue by KKotik** [Pannoniae/sodium-forge#63]
### Reproduction Steps
Just a random crash that I got when I was running on server.

### Crash Report File
https://pastebin.com/LdzuGK1h

### Mods list
A ton of, I am playing personal modpack with. (~400)

**Comment by Pannoniae** [comment]
This sounds like a race condition

**Comment by KKotik** [comment]
Wrong fork, I reported to the wrong fork, sorry.
