### ISSUE TITLE
Can you make this for 1.16.4 please ?

### ISSUE THREAD

**Issue by TreeV2** [Pannoniae/sodium-forge#8]
Can you make this for 1.16.4 please ?

**Comment by Pannoniae** [comment]
It's 1.16.4

**Comment by TreeV2** [comment]
> It's 1.16.4

if i use it on 1.16.4 my game insta crash on launch

**Comment by Pannoniae** [comment]
Send crash log please.

**Comment by TreeV2** [comment]
I send you log because crash log don t create 
[latest.log](https://github.com/Pannoniae/sodium-forge/files/5766854/latest.log)

**Comment by Pannoniae** [comment]
Oh. That's an old version. Recompile the latest commit and it should work.

**Comment by Pannoniae** [comment]
Pushed a new jar out so you don't have to compile yourself :) It's in releases.

**Comment by TreeV2** [comment]
> Pushed a new jar out so you don't have to compile yourself :) It's in releases.

idk my game crash again here log : 
[latest.log](https://github.com/Pannoniae/sodium-forge/files/5772510/latest.log)

**Comment by Pannoniae** [comment]
It's the same crash.

**Comment by TreeV2** [comment]
> It's the same crash.

idk why but i use your newer version and still crash

edit: so i find why it crash i use lithium forge beta and when i use lithium with the sodium the sodium crash
here is lithium what i use :
[Lithium.zip](https://github.com/Pannoniae/sodium-forge/files/5777908/Lithium.zip)

**Comment by Pannoniae** [comment]
This already includes Lithium. And Phosphor too. Don't need to use those. :)

**Comment by Pannoniae** [comment]
(sorry for the bad labeling, this is mainly for self-use so didn't separate stuff out to separate jars.)

**Comment by TreeV2** [comment]
> (sorry for the bad labeling, this is mainly for self-use so didn't separate stuff out to separate jars.)


Is this support optifine because i want use shaders and when i use sodium and optifine it crash

**Comment by Pannoniae** [comment]
yeah forget optifine, both modify rendering so that's a hard no for compatibility
