### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Matthysse** [Pannoniae/sodium-forge#9]
Hello!
Here is a crash I have, it doesn't generate a crash-report, here is the log.
https://pastebin.com/69P1P01U

**Comment by Pannoniae** [comment]
Hm, it seems like an incompatibility with Performant. Disable one of the mods.

**Comment by Matthysse** [comment]
Oh yes you're right, it works without it!
Does Performant adds benefits so it would be worth it to make it compatible or is it useless with all the optimization your mod brings?

**Comment by Pannoniae** [comment]
1. not my mod
2. it does optimise the game by a significant degree. However, there have been bugs in the past (like with every optimisation mod) so your mileage may vary :) I don't use it because it was incompatible with a bunch of stuff I'm using.

**Comment by Matthysse** [comment]
I know it isn't your mod, and ok thanks.

**Comment by Pannoniae** [comment]
<3
